MODE: str = "standalone"
HOST: str = "127.0.0.1"
PORT: int = 4545
DEFAULT_TENANT_ID: int = 1
DEFAULT_USER_NAME: str = "admin"
DEFAULT_USER_ID: int = 1
SINGLE_USER_MODE: bool = False
TEMP_DIR: str = 'temp'
SCHEDULER_LOCK: str = TEMP_DIR + '/' + 'fastapi_scheduler.lock'
