"""Added metadata field to Message table

Revision ID: 1ad3b8858682
Revises: 3f8e6786bde9
Create Date: 2024-10-21 14:53:30.868862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad3b8858682'
down_revision: Union[str, None] = '3f8e6786bde9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('source_metadata', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'source_metadata')
    # ### end Alembic commands ###
