"""application api key added

Revision ID: 02c1e28adc51
Revises: 5e805b526efa
Create Date: 2024-09-27 18:28:17.145394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core.db_models.utils


# revision identifiers, used by Alembic.
revision: str = '02c1e28adc51'
down_revision: Union[str, None] = '5e805b526efa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_application', sa.Column('application_api_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_application', 'application_api_key')
    # ### end Alembic commands ###
