"""added tenant id for guardrail tables and admin audit

Revision ID: 3e84bb67bced
Revises: 2d992e5994c8
Create Date: 2025-04-09 18:15:00.962745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core.db_models.utils


# revision identifiers, used by Alembic.
revision: str = '3e84bb67bced'
down_revision: Union[str, None] = '2d992e5994c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adding tenant_id column to guardrail tables by executing queries instead of using op.add_column
    # because it doesn't add columns with default values and NOT NULL together
    connection = op.get_bind()
    connection.execute(
        sa.text("ALTER TABLE guardrail ADD COLUMN tenant_id VARCHAR(255) NOT NULL DEFAULT 1"),
    )
    connection.execute(
        sa.text("ALTER TABLE response_template ADD COLUMN tenant_id VARCHAR(255) NOT NULL DEFAULT 1"),
    )
    connection.execute(
        sa.text("ALTER TABLE guardrail_version_history ADD COLUMN tenant_id VARCHAR(255) NOT NULL DEFAULT 1"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response_template', 'tenant_id')
    op.drop_column('guardrail_version_history', 'tenant_id')
    op.drop_column('guardrail', 'tenant_id')
    # ### end Alembic commands ###
