"""encryption_key_api_key_tables_added

Revision ID: bfcd4658b3bc
Revises: 5e805b526efa
Create Date: 2024-10-20 18:26:49.316781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core.db_models.utils


# revision identifiers, used by Alembic.
revision: str = 'bfcd4658b3bc'
down_revision: Union[str, None] = '5e805b526efa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_application_api_key',
    sa.Column('scope', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('expiry_time', sa.DateTime(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['ai_application.id'], name='fk_ai_application_policy_application_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_application_api_key_create_time'), 'ai_application_api_key', ['create_time'], unique=False)
    op.create_index(op.f('ix_ai_application_api_key_expiry_time'), 'ai_application_api_key', ['expiry_time'], unique=False)
    op.create_index(op.f('ix_ai_application_api_key_id'), 'ai_application_api_key', ['id'], unique=False)
    op.create_index(op.f('ix_ai_application_api_key_update_time'), 'ai_application_api_key', ['update_time'], unique=False)
    op.create_table('ai_application_encryption_key',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['ai_application.id'], name='fk_ai_application_policy_application_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_application_encryption_key_create_time'), 'ai_application_encryption_key', ['create_time'], unique=False)
    op.create_index(op.f('ix_ai_application_encryption_key_id'), 'ai_application_encryption_key', ['id'], unique=False)
    op.create_index(op.f('ix_ai_application_encryption_key_update_time'), 'ai_application_encryption_key', ['update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_application_encryption_key_update_time'), table_name='ai_application_encryption_key')
    op.drop_index(op.f('ix_ai_application_encryption_key_id'), table_name='ai_application_encryption_key')
    op.drop_index(op.f('ix_ai_application_encryption_key_create_time'), table_name='ai_application_encryption_key')
    op.drop_table('ai_application_encryption_key')
    op.drop_index(op.f('ix_ai_application_api_key_update_time'), table_name='ai_application_api_key')
    op.drop_index(op.f('ix_ai_application_api_key_id'), table_name='ai_application_api_key')
    op.drop_index(op.f('ix_ai_application_api_key_expiry_time'), table_name='ai_application_api_key')
    op.drop_index(op.f('ix_ai_application_api_key_create_time'), table_name='ai_application_api_key')
    op.drop_table('ai_application_api_key')
    # ### end Alembic commands ###
